version: '3.3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  discordbot:
    image: web
    command: bash -c "bundle exec rake chatbot:discord"
    depends_on:
      - db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rqdb
    ports:
      - "3000:3000"
    depends_on:
      - db
